version: '2'
services:
    jhipsterexemple-app:
        image: jhipsterexemple
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterexemple-mysql:3306/jhipsterexemple?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterexemple-mysql:
        extends:
            file: mysql.yml
            service: jhipsterexemple-mysql
